#!/usr/bin/env python3
__AUTHOR__ = "xvzf_opt"

# =====================================================================================
# Imports: External
# =====================================================================================
import re
import sys
import os
import argparse
from pathlib import Path
# prevent creation of compiled bytecode files
sys.dont_write_bytecode = True

# =====================================================================================
# Imports: Internal
# =====================================================================================
from recon.core import ReconNGXApp
from recon.core.output import colors

# =====================================================================================
# Functions
# =====================================================================================
def get_version():
    '''
    Reads the version file and parses the version number

    :returns: The recon-ngx version number
    :rtype: str
    '''
    version = None

    # Parse Version File
    path = os.path.join(Path(__file__).resolve().parent, "VERSION")
    with open(path, "r") as version_file:
        for line in version_file.readlines():
            if line.startswith("version"):
                version = line.split("=")[1].rstrip().strip()

    # Validate
    if not version:
        raise ValueError("Could not parse Recon-NGX version file.")

    return version

def launch_ui(args):
    '''
    Launches the recon-ngx User Interface

    :param args: The command line arguments
    :type args: argparse.Namespace
    '''
    # set up command completion
    try:
        import readline
    except ImportError:
        print(f"{colors.COLOR_R}[!] Module 'readline' not available. Tab complete disabled.{colors.COLOR_N}")
    else:
        import rlcompleter
        if 'libedit' in readline.__doc__:
            readline.parse_and_bind('bind ^I rl_complete')
        else:
            readline.parse_and_bind('tab: complete')
        readline.set_completer_delims(re.sub('[/-]', '', readline.get_completer_delims()))
        # for possible future use to format command completion output
        #readline.set_completion_display_matches_hook(display_hook)

    # Process Arguments
    flags = {
        "version": get_version(),
        "author": __AUTHOR__,
        "verbosity": args.verbosity,
        'check_version': args.check_version if not args.stealth else False,
        'marketplace_enabled': args.marketplace if not args.stealth else False,
        'modules_path': args.modules_path if args.modules_path else None,
        'data_path': args.data_path if args.data_path else None,
        'accessible' : args.accessible,
    }


    # Initialise Recon-NGX
    rngx = ReconNGXApp(**flags)

    # # check for and run script session
    if args.script_file:
        rngx.execute_script(args.script_file)
    # =====================================================================================
    # !!! Launch Recon-NGX !!!
    # =====================================================================================
    try:
        options = []
        if args.workspace:
            options.append(args.workspace)
        rngx.start(*options)
    except KeyboardInterrupt:
        print("")

# =====================================================================================
# Recon-NGX --> MAIN
# =====================================================================================
if __name__ == "__main__":
    description = f"%(prog)s - {__AUTHOR__}"
    parser = argparse.ArgumentParser(description=description)
    parser.add_argument('-w', help='Load/create a workspace', metavar='workspace', dest='workspace', action='store')
    parser.add_argument('-r', help='Load commands from a resource file', metavar='filename', dest='script_file', action='store')
    parser.add_argument('--modules-path', help='Overrides the directory to load modules from (dev-only)', dest='modules_path', action='store', default=None)
    parser.add_argument('--data-path', help='Overrides the data files directory (dev-only)', dest='data_path', action='store', default=None)
    parser.add_argument('--no-version', help='Disable version check', dest='check_version', default=True, action='store_false')
    parser.add_argument('--no-marketplace', help='Disable remote module management', dest='marketplace', default=True, action='store_false')
    parser.add_argument('--stealth', help='Disable all passive requests (--no-*)', dest='stealth', default=False, action='store_true')
    parser.add_argument('--accessible', help='Use accessible outputs when available', dest='accessible', default=False, action='store_true')
    parser.add_argument('--verbosity', help='Sets the output verbosity level [0, 1, 2]', dest='verbosity', default=1, type=int)
    parser.add_argument('--version', help='Displays the current version', action='version', version=get_version())

    # =====================================================================================
    # !!! START Recon-NGX !!!
    # =====================================================================================
    launch_ui(parser.parse_args())
