#!/usr/bin/env python3
__AUTHOR__ = "xvzf_opt"

# =====================================================================================
# Imports: External
# =====================================================================================
import re
import sys
import os
import argparse
# prevent creation of compiled bytecode files
sys.dont_write_bytecode = True

# =====================================================================================
# Imports: Internal
# =====================================================================================
from recon.core import base
from recon.core.output import ConsoleOutput

# =====================================================================================
# Functions
# =====================================================================================
def get_version():
    '''
    Reads the version file and parses the version number

    :returns: The recon-ngx version number
    :rtype: str
    '''
    version = None

    # Parse Version File
    path = os.path.join(os.path.dirname(__file__), 'VERSION')
    with open(path, "r") as version_file:
        for line in version_file.readlines():
            if line.startswith("version"):
                version = line.split("=")[1].rstrip().strip()

    # Validate
    if not version:
        raise ValueError("Could not parse Recon-ngX version file.")

    return version

def launch_ui(args):
    '''
    Launches the recon-ngx User Interface

    :param args: The command line arguments
    :type args: argparse.Namespace
    '''
    # set up command completion
    try:
        import readline
    except ImportError:
        print(f"{ConsoleOutput.COLOR_R}[!] Module 'readline' not available. Tab complete disabled.{ConsoleOutput.COLOR_N}")
    else:
        import rlcompleter
        if 'libedit' in readline.__doc__:
            readline.parse_and_bind('bind ^I rl_complete')
        else:
            readline.parse_and_bind('tab: complete')
        readline.set_completer_delims(re.sub('[/-]', '', readline.get_completer_delims()))
        # for possible future use to format command completion output
        #readline.set_completion_display_matches_hook(display_hook)

    # Process Arguments
    flags = {
        "version": get_version(),
        "author": __AUTHOR__,
        "verbosity": args.verbosity,
        'check': args.check if not args.stealth else False,
        'analytics': args.analytics if not args.stealth else False,
        'marketplace': args.marketplace if not args.stealth else False,
        'accessible' : args.accessible,
    }

    # instantiate framework
    recon_ngx = base.Recon(**flags)
    # check for and run script session
    if args.script_file:
        recon_ngx._do_script_execute(args.script_file)
    # launch the interactive session
    options = [base.Mode.CONSOLE]
    if args.workspace:
        options.append(args.workspace)
    try:
        recon_ngx.start(*options)
    except KeyboardInterrupt:
        print('')

# =====================================================================================
# Recon-ng eXtended --> MAIN
# =====================================================================================
if __name__ == "__main__":
    description = f"%(prog)s - {base.__author__}"
    parser = argparse.ArgumentParser(description=description)
    parser.add_argument('-w', help='Load/create a workspace', metavar='workspace', dest='workspace', action='store')
    parser.add_argument('-r', help='Load commands from a resource file', metavar='filename', dest='script_file', action='store')
    parser.add_argument('--no-version', help='Disable version check', dest='check', default=True, action='store_false')
    parser.add_argument('--no-analytics', help='Disable analytics reporting', dest='analytics', default=True, action='store_false')
    parser.add_argument('--no-marketplace', help='Disable remote module management', dest='marketplace', default=True, action='store_false')
    parser.add_argument('--stealth', help='Disable all passive requests (--no-*)', dest='stealth', default=False, action='store_true')
    parser.add_argument('--accessible', help='Use accessible outputs when available', dest='accessible', default=False, action='store_true')
    parser.add_argument('--verbosity', help='Sets the output verbosity level [0, 1, 2]', dest='verbosity', default=1, type=int)
    parser.add_argument('--version', help='Displays the current version', action='version', version=get_version())

    # =====================================================================================
    # !!! START RECON-NGX !!!
    # =====================================================================================
    launch_ui(parser.parse_args())
